package Modelo.Entidades;
// Generated 25/11/2019 10:24:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados  implements java.io.Serializable {


     private String idEstado;
     private String nombre;
     private Set tiempos = new HashSet(0);

    public Estados() {
    }

	
    public Estados(String idEstado) {
        this.idEstado = idEstado;
    }
    public Estados(String idEstado, String nombre, Set tiempos) {
       this.idEstado = idEstado;
       this.nombre = nombre;
       this.tiempos = tiempos;
    }
   
    public String getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(String idEstado) {
        this.idEstado = idEstado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTiempos() {
        return this.tiempos;
    }
    
    public void setTiempos(Set tiempos) {
        this.tiempos = tiempos;
    }




}


