package Modelo.Entidades;
// Generated 25/11/2019 10:24:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TiempoId generated by hbm2java
 */
public class TiempoId  implements java.io.Serializable {


     private int idCiudad;
     private Date fecha;

    public TiempoId() {
    }

    public TiempoId(int idCiudad, Date fecha) {
       this.idCiudad = idCiudad;
       this.fecha = fecha;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TiempoId) ) return false;
		 TiempoId castOther = ( TiempoId ) other; 
         
		 return (this.getIdCiudad()==castOther.getIdCiudad())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCiudad();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


