package Modelo.Entidades;
// Generated 25/11/2019 10:24:28 PM by Hibernate Tools 4.3.1



/**
 * Tiempo generated by hbm2java
 */
public class Tiempo  implements java.io.Serializable {


     private TiempoId id;
     private Ciudad ciudad;
     private Estados estados;
     private int idTiempo;
     private Integer tempMax;
     private Integer tempMin;

    public Tiempo() {
    }

	
    public Tiempo(TiempoId id, Ciudad ciudad, int idTiempo) {
        this.id = id;
        this.ciudad = ciudad;
        this.idTiempo = idTiempo;
    }
    public Tiempo(TiempoId id, Ciudad ciudad, Estados estados, int idTiempo, Integer tempMax, Integer tempMin) {
       this.id = id;
       this.ciudad = ciudad;
       this.estados = estados;
       this.idTiempo = idTiempo;
       this.tempMax = tempMax;
       this.tempMin = tempMin;
    }
   
    public TiempoId getId() {
        return this.id;
    }
    
    public void setId(TiempoId id) {
        this.id = id;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Estados getEstados() {
        return this.estados;
    }
    
    public void setEstados(Estados estados) {
        this.estados = estados;
    }
    public int getIdTiempo() {
        return this.idTiempo;
    }
    
    public void setIdTiempo(int idTiempo) {
        this.idTiempo = idTiempo;
    }
    public Integer getTempMax() {
        return this.tempMax;
    }
    
    public void setTempMax(Integer tempMax) {
        this.tempMax = tempMax;
    }
    public Integer getTempMin() {
        return this.tempMin;
    }
    
    public void setTempMin(Integer tempMin) {
        this.tempMin = tempMin;
    }




}


