package Modelo.Entidades;
// Generated 25/11/2019 10:24:28 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private String contraseña;

    public Usuario() {
    }

	
    public Usuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(String idUsuario, String contraseña) {
       this.idUsuario = idUsuario;
       this.contraseña = contraseña;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }




}


